CREATE TABLE IF NOT EXISTS REPORT(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Title TEXT,
    Loc TEXT NOT NULL,
    Des TEXT NOT NULL,
    Img TEXT,
    Vid TEXT,
    Author TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORS(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name TEXT NOT NULL,
    Username TEXT NOT NULL UNIQUE,
    Email TEXT NOT NULL UNIQUE,
    Pwd TEXT NOT NULL
);